#!/bin/bash
# maravento.com

# Bandata for Squid Reports
# Data Plan for LAN

# Instructions:
# Configuration is read from /etc/proxymon/proxymon.env (generated by proxymon.sh install)
# Log output: /var/log/bandata.log
# Default limits: max 1G day / 5G week / 20G month
# Limits can use M, G or B suffix (e.g. 500M, 1G, 1.5G)
# bandata excludes weekends

# Root check
if [ "$(id -u)" != "0" ]; then
    echo "ERROR: This script must be run as root"
    exit 1
fi

# Dependency check — abort early with a clear message instead of
# failing silently partway through ipset/iptables operations
for cmd in ipset iptables numfmt; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "ERROR: required command '$cmd' not found. Install it before running this script."
        exit 1
    fi
done

# Prevent overlapping runs
SCRIPT_LOCK="/var/lock/$(basename "$0" .sh).lock"
exec 200>"$SCRIPT_LOCK"
if ! flock -n 200; then
    echo "Script $(basename "$0") is already running"
    exit 1
fi

### LOG
BANDATA_LOG="/var/log/bandata.log"
touch "$BANDATA_LOG" 2>/dev/null || true
exec >> "$BANDATA_LOG" 2>&1

echo "----------------------------------------------------------------"
echo "$(date '+%Y-%m-%d %H:%M:%S') — Bandata start"
echo "----------------------------------------------------------------"

# Verify logrotate config exists for this log; create it if missing (self-contained)
logrotate_conf="/etc/logrotate.d/bandata"
if [ ! -f "$logrotate_conf" ]; then
    cat > "$logrotate_conf" <<'EOF'
/var/log/bandata.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    create 640 root adm
}
EOF
    chmod 644 "$logrotate_conf"
    chown root:root "$logrotate_conf"
    echo "Created logrotate config: $logrotate_conf"
fi

### CONFIGURATION
PROXYMON_ENV="/etc/proxymon/proxymon.env"
if [ ! -f "$PROXYMON_ENV" ]; then
    echo "ERROR: $PROXYMON_ENV not found. Run proxymon.sh install to generate it."
    exit 1
fi
_env_owner=$(stat -c '%U' "$PROXYMON_ENV" 2>/dev/null)
_env_perms=$(stat -c '%a' "$PROXYMON_ENV" 2>/dev/null)
_env_group_digit="${_env_perms: -2:1}"
_env_other_digit="${_env_perms: -1}"
if [ "$_env_owner" != "root" ] || [[ "$_env_group_digit" =~ [2367] ]] || [[ "$_env_other_digit" =~ [2367] ]]; then
    echo "ERROR: $PROXYMON_ENV has unsafe owner/permissions (owner=$_env_owner perms=$_env_perms)."
    echo "Expected owner root with no group/other write access. Refusing to source it."
    exit 1
fi
# shellcheck source=/etc/proxymon/proxymon.env
source "$PROXYMON_ENV"

### DERIVED VARIABLES
# local aliases for readability
lan="$LAN"
range="$REPORT_IP_GLOB"
report="$REPORT_PATH"
allow_list="$ALLOW_LIST"
block_list_day="$BLOCK_LIST_DAY"
block_list_week="$BLOCK_LIST_WEEK"
block_list_month="$BLOCK_LIST_MONTH"
realname="$REALNAME_CFG"
skipuser="$SKIPUSERS_CFG"

# Validate LAN interface — required for all iptables rules below
if [ -z "$lan" ]; then
    echo "ERROR: LAN is empty in $PROXYMON_ENV"
    exit 1
fi
if [ ! -e "/sys/class/net/$lan" ]; then
    echo "ERROR: network interface '$lan' (from LAN in $PROXYMON_ENV) does not exist on this system"
    echo "Available interfaces: $(ls /sys/class/net 2>/dev/null | tr '\n' ' ')"
    exit 1
fi

# today
today=$(date +"%u")
# reorganize IP
reorganize="sort -t . -k 1,1n -k 2,2n -k 3,3n -k 4,4n"
# Create folders if they don't exist
[ -d "$ACL_PATH" ]         || mkdir -p "$ACL_PATH"
[ -d "$ACL_MAC_PATH" ]     || mkdir -p "$ACL_MAC_PATH"
[ -d "$ACL_BANDATA_PATH" ] || mkdir -p "$ACL_BANDATA_PATH"
# Create ACL files if they don't exist
touch "$ALLOW_LIST" "$BLOCK_LIST_DAY" "$BLOCK_LIST_WEEK" "$BLOCK_LIST_MONTH"

if [ "$UNIFI_HOTSPOT_ENABLED" = true ]; then
    [ -d "$HOTSPOT_PATH" ] || mkdir -p "$HOTSPOT_PATH"
fi

### BANDWIDTH LIMITS VALIDATION
# Convert and validate MAX_BANDWIDTH_* before any comparison is made.
# If numfmt fails (empty/invalid value), abort instead of silently
# treating the limit as 0, which would block the entire network.
max_bw_day=$(LC_ALL=C numfmt --from=iec "${MAX_BANDWIDTH_DAY/,/.}" 2>/dev/null)
if [ -z "$max_bw_day" ]; then
    echo "ERROR: invalid MAX_BANDWIDTH_DAY value in $PROXYMON_ENV: '${MAX_BANDWIDTH_DAY}'"
    echo "Expected format: number with optional M or G suffix (e.g. 500M, 1G, 1.5G)"
    exit 1
fi

max_bw_week=$(LC_ALL=C numfmt --from=iec "${MAX_BANDWIDTH_WEEK/,/.}" 2>/dev/null)
if [ -z "$max_bw_week" ]; then
    echo "ERROR: invalid MAX_BANDWIDTH_WEEK value in $PROXYMON_ENV: '${MAX_BANDWIDTH_WEEK}'"
    echo "Expected format: number with optional M or G suffix (e.g. 500M, 1G, 1.5G)"
    exit 1
fi

max_bw_month=$(LC_ALL=C numfmt --from=iec "${MAX_BANDWIDTH_MONTH/,/.}" 2>/dev/null)
if [ -z "$max_bw_month" ]; then
    echo "ERROR: invalid MAX_BANDWIDTH_MONTH value in $PROXYMON_ENV: '${MAX_BANDWIDTH_MONTH}'"
    echo "Expected format: number with optional M or G suffix (e.g. 500M, 1G, 1.5G)"
    exit 1
fi

### BANDATA DAY (daily)
echo "Running Bandata Day..."
# path to day report
day_logs=$report/$(date +"%Y%m%d")
# bandata day rule
if [[ "$today" -eq 6 || "$today" -eq 7 ]]; then
    echo "Weekend Excluded"
    : > "$block_list_day"
else
    if [ ! -d "$day_logs" ]; then
        echo "Day report folder not found: $day_logs"
        : > "$block_list_day"
    else
        _tmp_day=$(mktemp)
        _subshell_ok=0
        (
            cd "$day_logs" || { echo "ERROR: cannot cd into $day_logs" >&2; exit 1; }
            shopt -s nullglob
            for file in $range; do
                total=$(awk '$1=="total:" {print $2}' "$file")
                if [[ "$total" =~ ^[0-9]+$ ]] && (( total > max_bw_day )); then
                    echo "$file"
                elif [ -n "$total" ] && ! [[ "$total" =~ ^[0-9]+$ ]]; then
                    echo "WARNING: non-numeric total '$total' in $day_logs/$file — skipping" >&2
                fi
            done
            exit 0
        ) > "$_tmp_day" && _subshell_ok=1

        if [ "$_subshell_ok" -eq 1 ]; then
            grep -wvFf <(grep -v '^[[:space:]]*$' "$allow_list") "$_tmp_day" | $reorganize | uniq > "${block_list_day}.tmp" \
                && mv -f "${block_list_day}.tmp" "$block_list_day"
        else
            echo "ERROR: subshell failed for $day_logs — keeping existing block list"
        fi
        rm -f "$_tmp_day"
    fi
    
    day_count=$(wc -l < "$block_list_day" 2>/dev/null || echo 0)
    if [ "$day_count" -gt 0 ]; then
        echo "Daily Blocked:"
        sed 's/^/    /' "$block_list_day"
    else
        echo "No daily blocks"
    fi
fi
echo "OK"

### BANDWIDTH WEEK (weekly MON-FRI)
# NOTE: uses GNU date (coreutils) relative-date syntax ("last monday",
# "+1 month -1 day"). Not portable to BSD/macOS date. This project
# targets Linux only (already requires ipset/iptables).
echo "Running Bandata Week..."

if [ "$today" -eq 1 ]; then
    week_dirs=()
    for x in {0..4}; do
        d="$report/$(date -d "last monday +$x days" +'%Y%m%d')"
        [ -d "$d" ] && week_dirs+=("$d")
    done

    if [ ${#week_dirs[@]} -eq 0 ]; then
        echo "No weekday report folders found for last week"
        : > "$block_list_week"
    else
        folders=$(find "${week_dirs[@]}" -maxdepth 1 -type f -name "$range")
        totals=$(echo "$folders" | xargs -r -I {} awk '/^total:/{sub(".*/", "", FILENAME); print FILENAME" "$NF}' {})
        ips=$(echo "$totals" | awk '{ arr[$1]+=$2 } END { for (key in arr) printf("%s\t%s\n", arr[key], key) }' | sort -k1,1)
        echo "$ips" | awk -v max="$max_bw_week" '$1 > max {print $2}' | grep -wvFf <(grep -v '^[[:space:]]*$' "$allow_list") | $reorganize | uniq > "${block_list_week}.tmp" \
            && mv -f "${block_list_week}.tmp" "$block_list_week"
    fi

    week_count=$(wc -l < "$block_list_week" 2>/dev/null || echo 0)
    if [ "$week_count" -gt 0 ]; then
        echo "Weekly Blocked:"
        sed 's/^/    /' "$block_list_week"
    else
        echo "No weekly blocks"
    fi
else
    echo "Weekly check runs on Monday only"
fi
echo "OK"

### BANDATA MONTH (monthly)
echo "Running Bandata Month..."

# Build weekday directories for current month (excluding weekends)
month_prefix=$(date +"%Y%m")
days_in_month=$(date -d "$(date +%Y-%m-01) +1 month -1 day" +%d)
month_dirs=()
for d in $(seq -w 1 "$days_in_month"); do
    day_path="$report/${month_prefix}${d}"
    [ -d "$day_path" ] || continue
    dow=$(date -d "${month_prefix:0:4}-${month_prefix:4:2}-${d}" +%u)
    [ "$dow" -ge 6 ] && continue
    month_dirs+=("$day_path")
done

if [ ${#month_dirs[@]} -eq 0 ]; then
    echo "No weekday report folders found for current month"
    : > "$block_list_month"
else
    folders=$(find "${month_dirs[@]}" -maxdepth 1 -type f -name "$range")
    totals=$(echo "$folders" | xargs -r -I {} awk '/^total:/{sub(".*/", "", FILENAME); print FILENAME" "$NF}' {})
    ips=$(echo "$totals" | awk '{ arr[$1]+=$2 } END { for (key in arr) printf("%s\t%s\n", arr[key], key) }' | sort -k1,1)
    echo "$ips" | awk -v max="$max_bw_month" '$1 > max {print $2}' | grep -wvFf <(grep -v '^[[:space:]]*$' "$allow_list") | $reorganize | uniq > "${block_list_month}.tmp" \
        && mv -f "${block_list_month}.tmp" "$block_list_month"
fi

month_count=$(wc -l < "$block_list_month" 2>/dev/null || echo 0)
if [ "$month_count" -gt 0 ]; then
    echo "Monthly Blocked:"
    sed 's/^/    /' "$block_list_month"
else
    echo "No monthly blocks"
fi
echo "OK"

### IPSET/IPTABLES FOR BANDATA
echo "Running Ipset/Iptables Rules..."
ipset -! create bandata hash:net family inet hashsize 1024 maxelem 65536
ipset -! create bandata_new hash:net family inet hashsize 1024 maxelem 65536
ipset -! flush bandata_new

# NAT
sysctl -w net.ipv4.ip_forward=1 >/dev/null 2>&1

# Load IPs to bandata_new
all_bans=$(cat "$block_list_day" "$block_list_week" "$block_list_month" | $reorganize | uniq)

if [ -n "$all_bans" ]; then
    for ip in $all_bans; do
        ipset -exist add bandata_new "$ip"
    done
fi

# Atomic swap: bandata_new replaces bandata with no window of empty set
if ipset swap bandata_new bandata; then
    ipset destroy bandata_new
else
    echo "ERROR: ipset swap failed — bandata_new left in place for inspection, bandata not updated"
fi

if [ -n "$all_bans" ]; then
    echo ""
    echo "FINAL BAN SUMMARY:"
    ipset list bandata 2>/dev/null | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | $reorganize | while IFS= read -r ip; do
        # Check which category this IP belongs to
        if grep -qxF "$ip" "$block_list_day" 2>/dev/null; then
            cat_type="DAILY"
        elif grep -qxF "$ip" "$block_list_week" 2>/dev/null; then
            cat_type="WEEKLY"
        elif grep -qxF "$ip" "$block_list_month" 2>/dev/null; then
            cat_type="MONTHLY"
        else
            cat_type="UNKNOWN"
        fi
        echo "  $ip [$cat_type]"
    done
else
    echo "There are no IPs in bandata"
fi

echo ""
echo "Applying Iptables Rules..."

# Create dedicated chains if they don't exist
iptables -N BANDATA_FWD 2>/dev/null
iptables -N BANDATA_IN  2>/dev/null

# Jump into dedicated chains from FORWARD/INPUT position 1
iptables -C FORWARD -i "$lan" -j BANDATA_FWD 2>/dev/null || \
iptables -I FORWARD 1 -i "$lan" -j BANDATA_FWD

iptables -C INPUT -i "$lan" -j BANDATA_IN 2>/dev/null || \
iptables -I INPUT 1 -i "$lan" -j BANDATA_IN

# Populate BANDATA_FWD (order matters within this chain only)
iptables -C BANDATA_FWD -m set --match-set bandata src -p udp --dport 53 -j ACCEPT 2>/dev/null || \
iptables -A BANDATA_FWD -m set --match-set bandata src -p udp --dport 53 -j ACCEPT

iptables -C BANDATA_FWD -m set --match-set bandata src -p tcp --dport 80 -j ACCEPT 2>/dev/null || \
iptables -A BANDATA_FWD -m set --match-set bandata src -p tcp --dport 80 -j ACCEPT

iptables -C BANDATA_FWD -m set --match-set bandata src -j DROP 2>/dev/null || \
iptables -A BANDATA_FWD -m set --match-set bandata src -j DROP

# Populate BANDATA_IN
iptables -C BANDATA_IN -m set --match-set bandata src -p tcp --dport 18081 -j ACCEPT 2>/dev/null || \
iptables -A BANDATA_IN -m set --match-set bandata src -p tcp --dport 18081 -j ACCEPT

iptables -C BANDATA_IN -m set --match-set bandata src -j DROP 2>/dev/null || \
iptables -A BANDATA_IN -m set --match-set bandata src -j DROP

# NAT redirect (PREROUTING is unaffected by the chain restructure)
iptables -t nat -C PREROUTING -i "$lan" -m set --match-set bandata src -p tcp --dport 80 -j REDIRECT --to-port 18081 2>/dev/null || \
iptables -t nat -I PREROUTING 1 -i "$lan" -m set --match-set bandata src -p tcp --dport 80 -j REDIRECT --to-port 18081

echo "Done"
printf "\n"

### WARNING PAGE UPDATE
# Sync quota values from proxymon.env into warning.html
# Values are delimited by HTML comments: <!-- bw-day --> ... <!-- /bw-day -->
WARNING_HTML="/var/www/proxymon/warning/warning.html"
if [ -f "$WARNING_HTML" ]; then
    sed -i \
        -e "s#<!-- bw-day -->[^<]*<!-- /bw-day -->#<!-- bw-day -->${MAX_BANDWIDTH_DAY}<!-- /bw-day -->#" \
        -e "s#<!-- bw-week -->[^<]*<!-- /bw-week -->#<!-- bw-week -->${MAX_BANDWIDTH_WEEK}<!-- /bw-week -->#" \
        -e "s#<!-- bw-month -->[^<]*<!-- /bw-month -->#<!-- bw-month -->${MAX_BANDWIDTH_MONTH}<!-- /bw-month -->#" \
        "$WARNING_HTML"
fi

# Generates realname.cfg and skipuser.cfg for Lightsquid reports.
# ACL format expected: a;MAC;IP;HOSTNAME;
# Output format: "IP HOSTNAME"
update_lightsquid_realname() {
    # Files to exclude from realname.cfg (sent to skipuser.cfg instead).
    # Use filenames only, space-separated. Empty string disables exclusion.
    local exclude_acls="mac-transparent.txt mac-unlimited.txt"

    # Extract "IP HOSTNAME" from ACL line "a;MAC;IP;HOSTNAME;"
    extract_ip_hostname() {
        awk -F';' 'NF >= 4 && $3 ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ {print $3, $4}'
    }

    # Check if a basename matches the exclude list (exact match, no regex)
    is_excluded() {
        local basename="$1"
        local f
        for f in $exclude_acls; do
            [ "$basename" = "$f" ] && return 0
        done
        return 1
    }

    process_hotspot() {
        [ -f "$HOTSPOT_PATH/mac-hotspot.txt" ] || return
        awk -F';' '$3 != "0.0.0.0" && NF >= 4 {print $3, $4}' "$HOTSPOT_PATH/mac-hotspot.txt"
    }

    process_acls() {
        local mode="$1"  # "include" or "exclude"
        local file
        find "$ACL_MAC_PATH" -maxdepth 1 -type f -iname 'mac-*' | while read -r file; do
            local bn
            bn=$(basename "$file")
            if [ "$mode" = "include" ]; then
                is_excluded "$bn" && continue
            else
                is_excluded "$bn" || continue
            fi
            extract_ip_hostname < "$file"
        done
    }

    local sort_ips="sort -u -t . -k 1,1n -k 2,2n -k 3,3n -k 4,4n"
    local hotspot_out="" acl_out skip_out

    if [ "$UNIFI_HOTSPOT_ENABLED" = true ]; then
        hotspot_out=$(process_hotspot)
    fi
    acl_out=$(process_acls include)
    skip_out=$(process_acls exclude)

    local final_output skip_output
    final_output=$(printf "%s\n%s\n" "$hotspot_out" "$acl_out" | sed '/^$/d' | $sort_ips)
    skip_output=$(printf "%s\n" "$skip_out" | sed '/^$/d' | $sort_ips)

    if [ -z "$final_output" ]; then
        echo "  No MAC data processed for realname.cfg"
    else
        echo "$final_output" > "${realname}.tmp" && mv -f "${realname}.tmp" "$realname"
    fi

    if [ -z "$skip_output" ]; then
        echo "  No excluded data for skipuser.cfg"
    else
        echo "$skip_output" > "${skipuser}.tmp" && mv -f "${skipuser}.tmp" "$skipuser"
    fi
}
# ==============================================================================
# LIGHTSQUID REALNAME UPDATE
# ==============================================================================
if [[ "${UPDATE_REALNAME:-false}" == "true" ]]; then
    update_lightsquid_realname
fi
