Output	/var/www/proxymon/squidanalyzer/output
WebUrl	/proxymon/squidanalyzer/resources/
LogFile	/var/log/squid/access.log
UseClientDNSName	0
DNSLookupTimeout	0.0001
NetworkAlias	/var/www/proxymon/squidanalyzer/etc/network-aliases
UserAlias	/var/www/proxymon/squidanalyzer/etc/user-aliases
OrderNetwork	bytes
OrderUser	bytes
OrderUrl	bytes
OrderMime	bytes
UrlReport	1
UrlHitsOnly	0
UserReport	1
QuietMode	1
CostPrice	0
Currency	&euro;
TopNumber	100
TopStorage	0
Exclude	/var/www/proxymon/squidanalyzer/etc/excluded
Include	/var/www/proxymon/squidanalyzer/etc/included
DateFormat	%y-%m-%d
AnonymizeLogin	0
SiblingHit	1
TransfertUnit	BYTES
MinPie		2
WriteDelay	3600
TopUrlUser	10
